/*
 * Copyright 2015 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * The origin of this file is
 * https://github.com/tianocore/edk2.git:MdePkg/Include/IndustryStandard/Tpm20.h
 * published under BSD license. It can not be copied as is, as it collides
 * with some of the definitions of this package.
 */

#ifndef __TPM2_TPM_TYPES_H
#define __TPM2_TPM_TYPES_H

#include "Capabilities.h"
#include "Implementation.h"
typedef UINT32 TPM_SPEC;

#include "tpm_types.h"

/*
 * The below enum is just a pile of all return codes defined in functions in
 * part 4 of the spec.
 *
 * TODO: map these properly into Format-One error reporting.
 */
enum {
  RC_ActivateCredential_credentialBlob,
  RC_ActivateCredential_keyHandle,
  RC_ActivateCredential_secret,
  RC_CertifyCreation_creationTicket,
  RC_CertifyCreation_inScheme,
  RC_CertifyCreation_signHandle,
  RC_Certify_inScheme,
  RC_Certify_signHandle,
  RC_ClockSet_newTime,
  RC_Commit_P1,
  RC_Commit_s2,
  RC_Commit_signHandle,
  RC_Commit_y2,
  RC_ContextLoad_context,
  RC_CreatePrimary_inPublic,
  RC_CreatePrimary_inSensitive,
  RC_Create_inPublic,
  RC_Create_inSensitive,
  RC_Create_parentHandle,
  RC_Duplicate_encryptionKeyIn,
  RC_Duplicate_newParentHandle,
  RC_Duplicate_objectHandle,
  RC_Duplicate_symmetricAlg,
  RC_ECC_Parameters_curveID,
  RC_ECDH_KeyGen_keyHandle,
  RC_ECDH_ZGen_keyHandle,
  RC_ECDH_ZGen_inPoint,
  RC_EncryptDecrypt_inData,
  RC_EncryptDecrypt_ivIn,
  RC_EncryptDecrypt_keyHandle,
  RC_EncryptDecrypt_mode,
  RC_EventSequenceComplete_sequenceHandle,
  RC_EvictControl_objectHandle,
  RC_EvictControl_persistentHandle,
  RC_GetCapability_property,
  RC_GetCommandAuditDigest_signHandle,
  RC_GetCommandAuditDigest_inScheme,
  RC_GetSessionAuditDigest_inScheme,
  RC_GetSessionAuditDigest_sessionHandle,
  RC_GetSessionAuditDigest_signHandle,
  RC_GetTime_inScheme,
  RC_GetTime_signHandle,
  RC_HMAC_handle,
  RC_HMAC_hashAlg,
  RC_HMAC_Start_handle,
  RC_HMAC_Start_hashAlg,
  RC_HierarchyChangeAuth_newAuth,
  RC_Import_duplicate,
  RC_Import_encryptionKey,
  RC_Import_inSymSeed,
  RC_Import_objectPublic,
  RC_Import_parentHandle,
  RC_IncrementalSelfTest_toTest,
  RC_Load_inPrivate,
  RC_Load_inPublic,
  RC_Load_parentHandle,
  RC_LoadExternal_hierarchy,
  RC_LoadExternal_inPublic,
  RC_MakeCredential_credential,
  RC_MakeCredential_handle,
  RC_NV_Certify_signHandle,
  RC_NV_Certify_inScheme,
  RC_NV_ChangeAuth_newAuth,
  RC_NV_DefineSpace_auth,
  RC_NV_DefineSpace_authHandle,
  RC_NV_DefineSpace_publicInfo,
  RC_NV_Extend_nvIndex,
  RC_NV_Increment_nvIndex,
  RC_NV_ReadLock_nvIndex,
  RC_NV_SetBits_nvIndex,
  RC_NV_UndefineSpace_nvIndex,
  RC_NV_UndefineSpaceSpecial_nvIndex,
  RC_NV_WriteLock_nvIndex,
  RC_ObjectChangeAuth_newAuth,
  RC_ObjectChangeAuth_objectHandle,
  RC_ObjectChangeAuth_parentHandle,
  RC_PCR_SetAuthPolicy_authPolicy,
  RC_PCR_SetAuthPolicy_pcrNum,
  RC_PolicyAuthorize_approvedPolicy,
  RC_PolicyAuthorize_checkTicket,
  RC_PolicyAuthorize_keySign,
  RC_PolicyCommandCode_code,
  RC_PolicyCpHash_cpHashA,
  RC_PolicyLocality_locality,
  RC_PolicyNV_operandB,
  RC_PolicyNameHash_nameHash,
  RC_PolicyNvWritten_writtenSet,
  RC_PolicyOR_pHashList,
  RC_PolicyPCR_pcrDigest,
  RC_PolicySecret_cpHashA,
  RC_PolicySecret_expiration,
  RC_PolicySecret_nonceTPM,
  RC_PolicySigned_auth,
  RC_PolicySigned_cpHashA,
  RC_PolicySigned_expiration,
  RC_PolicySigned_nonceTPM,
  RC_PolicyTicket_cpHashA,
  RC_PolicyTicket_policySession,
  RC_PolicyTicket_ticket,
  RC_PolicyTicket_timeout,
  RC_Quote_inScheme,
  RC_Quote_signHandle,
  RC_RSA_Decrypt_inScheme,
  RC_RSA_Decrypt_keyHandle,
  RC_RSA_Decrypt_label,
  RC_RSA_Encrypt_inScheme,
  RC_RSA_Encrypt_keyHandle,
  RC_RSA_Encrypt_label,
  RC_Rewrap_inDuplicate,
  RC_Rewrap_inSymSeed,
  RC_Rewrap_newParent,
  RC_Rewrap_oldParent,
  RC_SequenceComplete_sequenceHandle,
  RC_SequenceUpdate_sequenceHandle,
  RC_SetCommandCodeAuditStatus_auditAlg,
  RC_SetPrimaryPolicy_authPolicy,
  RC_Shutdown_shutdownType,
  RC_Sign_digest,
  RC_Sign_inScheme,
  RC_Sign_keyHandle,
  RC_Sign_validation,
  RC_StartAuthSession_bind,
  RC_StartAuthSession_encryptedSalt,
  RC_StartAuthSession_nonceCaller,
  RC_StartAuthSession_symmetric,
  RC_StartAuthSession_tpmKey,
  RC_Startup_startupType,
  RC_Unseal_itemHandle,
  RC_VerifySignature_keyHandle,
  RC_VerifySignature_signature,
  RC_ZGen_2Phase_counter,
  RC_ZGen_2Phase_inQeB,
  RC_ZGen_2Phase_inQsB,
  RC_ZGen_2Phase_inScheme,
  RC_ZGen_2Phase_keyA,
};

enum {
  TPM_RCS_ATTRIBUTES,
  TPM_RCS_HANDLE,
  TPM_RCS_KEY,
  TPM_RCS_SIZE,
  TPM_RCS_TYPE,
  TPM_RCS_VALUE,
};

#endif  // __TPM2_TPM_TYPES_H
